Repository hassio-addons/addon-bitwarden, pull requests merged in 2022-12, with the labels that each got.

#230 ⬆️ Upgrades add-on base image to 6.2.0
  bitwarden/Dockerfile
  bitwarden/build.yaml
Labels: dependencies

#231 :hammer: Migrate old-style S6 scripts to s6-rc.d
  bitwarden/rootfs/etc/s6-overlay/s6-rc.d/init-nginx/dependencies.d/base
  bitwarden/rootfs/etc/s6-overlay/s6-rc.d/init-nginx/run
  bitwarden/rootfs/etc/s6-overlay/s6-rc.d/init-nginx/type
  bitwarden/rootfs/etc/s6-overlay/s6-rc.d/init-nginx/up
  bitwarden/rootfs/etc/s6-overlay/s6-rc.d/nginx/dependencies.d/init-nginx
  bitwarden/rootfs/etc/s6-overlay/s6-rc.d/nginx/dependencies.d/vaultwarden
  bitwarden/rootfs/etc/s6-overlay/s6-rc.d/nginx/finish
  bitwarden/rootfs/etc/s6-overlay/s6-rc.d/nginx/run
  bitwarden/rootfs/etc/s6-overlay/s6-rc.d/nginx/type
  bitwarden/rootfs/etc/s6-overlay/s6-rc.d/user/contents.d/init-nginx
  bitwarden/rootfs/etc/s6-overlay/s6-rc.d/user/contents.d/nginx
  bitwarden/rootfs/etc/s6-overlay/s6-rc.d/user/contents.d/vaultwarden
  bitwarden/rootfs/etc/s6-overlay/s6-rc.d/vaultwarden/dependencies.d/base
  bitwarden/rootfs/etc/s6-overlay/s6-rc.d/vaultwarden/finish
  bitwarden/rootfs/etc/s6-overlay/s6-rc.d/vaultwarden/run
  bitwarden/rootfs/etc/s6-overlay/s6-rc.d/vaultwarden/type
  bitwarden/rootfs/etc/services.d/bitwarden/finish
  bitwarden/rootfs/etc/services.d/nginx/finish
Labels: maintenance

#232 ⬆️ Upgrades Vaultwarden to 1.27.0
  bitwarden/Dockerfile
Labels: dependencies, minor

#233 📚 Fix step reference in installation steps
  bitwarden/DOCS.md
Labels: documentation
